name: brain-tumor-detection
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip=23.1.2
    - numpy=1.24.3
    - pandas=2.0.3
    - matplotlib=3.7.2
    - seaborn=0.12.2
    - scikit-learn=1.3.0
    - jupyter=1.0.0
    - notebook=7.0.2
    - cudatoolkit=11.8  # Only needed for GPU support
    - pip:
        - tensorflow==2.13.0
        - torch==2.0.1
        - torchvision==0.15.2
        - opencv-python==4.8.0.76
        - pillow==10.0.0
        - tqdm==4.65.0
        - nibabel==5.1.0  # For handling medical imaging formats
        - albumentations==1.3.1  # For image augmentation